# -*- coding: utf-8 -*-
"""EDA Matplotlib Session-02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPWY2nbLBwfS2E2p6DK8YUsZXkHOWJgh

Matplotlib
"""

#Importing the Libraries
import matplotlib.pyplot as plt
import numpy as np

"""Basic Graph"""

x = np.arange(1,11)
x

y = x**2
y

# simple plot (plt.plot()) gives the line graph
# plot(x,y)
plt.plot(x, y)

plt.plot(x, y)
plt.show() #REMOVES THIS LINE : [<matplotlib.lines.Line2D at 0x7ab35828a5f0>]

plt.plot(x, y, color = "purple", marker =  "o", linestyle = "-", linewidth = 2)
plt.xlabel("X-Axis", size = 12, loc = "center")
plt.ylabel("Y-Axis", size = 12, loc = "center")
plt.title("Line Plot", color = "purple", size= 16, loc = "Center")
plt.show()

plt.plot(x, y, label = "x^2", color = "purple", marker =  "o", markersize = 5, markeredgecolor = "pink",  linestyle = "-", linewidth = 2)
plt.xlabel("X-Axis", size = 12, loc = "center", color = "purple")
plt.ylabel("Y-Axis", size = 12, loc = "center", color = "purple")
plt.title("Line Plot", fontdict = {"color" : "purple", "size" : 16},  loc = "Center", style = "oblique")
plt.grid(color = "pink")
plt.legend(loc = "upper left")

#plt.xticks([1,2,3,4,5,6])
# plt.xticks([1,2,3,4,5,6,7,8,9,10])

# if you havent given the label in plt.plot then you will have to write
# plt.lagend(["x^2"])

# remove borders
plt.gca().spines["top"].set_visible(False)
plt.gca().spines["bottom"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.gca().spines["left"].set_visible(False)
plt.tick_params(color = "pink")
plt.show()

# short hand notation
# format = "[color][marker][line]"

plt.plot(x,y,'r^--', label = "2X")
# r is for red color
# ^ is for the marker style
# -- is the line design

"""changing size of the plots"""

plt.figure(figsize = (6, 3))
plt.title("My figure graph")
plt.plot(x, y, 'go-', label = "2X")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.legend(loc = "upper left")
plt.show()
# figsize = (width, height) ... figsize = (10, 5)  ...
# 10 inches in width and 5  inches in height

"""Other plots"""

plt.bar(x,y, label = "Bar Plot", color = "Purple")
plt.xlabel("Y-axis", color = "grey", size = 12)
plt.title("Bar Plot", color = "Purple", size = 16)

plt.gca().spines["top"].set_visible(False)
plt.gca().spines["right"].set_visible(False)
plt.gca().spines["bottom"].set_color("grey")
plt.gca().spines["left"].set_color("grey")
# plt.gca().set_facecolor('pink')


# changing the color of tick axis values
plt.tick_params(axis = "both", color = "purple")

plt.show()

"""Sub plots"""

plt.figure(figsize = (20,5)) # longer width - 2 plots side by side

plt.subplot(1, 2, 1) # rows, columns, panel selected

plt.subplot(1, 2, 2) # rows, columns, panel selected

plt.show()

plt.figure(figsize = (20,5)) # longer width - 2 plots side by side

plt.subplot(1, 3, 1) # rows, columns, panel selected

plt.subplot(1, 3, 2) # rows, columns, panel selected

plt.subplot(1, 3, 3) # rows, columns, panel selected

plt.show()

#plt.title("kg4n4r")


plt.figure(figsize = (20,5)) # longer width - 2 plots side by side


plt.subplot(1, 2, 1) # rows, columns, panel selected
plt.plot(x,y, color = "purple")
plt.legend(["X^2", "vertical Line"])
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

plt.subplot(1, 2, 2) # rows, columns, panel selected
plt.plot(x,-1 * y, color = "purple")
plt.legend(["-X^2", "Horizontal Line"])
plt.xlabel("X")
plt.ylabel("X Squared")


# under panel, make its graph

plt.show()

fig, axes = plt.subplots(2, 3)



