# -*- coding: utf-8 -*-
"""Python Session 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PDmVSPyNj7fi01YervaNBfI6eXozTotY

# Python First Session

# Python
"""

######### It's my first class

2 + 3

"""## Basic Concepts of displaying the data"""

print("Hello world!")

help(print)

print("My name"," is ","Maimoona Khilji.")

print("Hello","Universe",sep="-----")

print("My name is Maimoona.",1234,5667,"Peshawar", sep="._.")

print("My name is Maimoona.",end=" ")
print("My age is 23.",end=" ")
print("I am from Peshawar.")

print("abc", True, 12345,1234, sep=",")

"""## Variables

containers to store the data.
"""

NamE = "Maimoona Khilji"

NamE

Age  = 23

print("my age is 23")

print("my age is Age")

print("my Age is", Age)

print(Name)
print(Age)

Name

Age

Name
Age



a  = "alphabets"

Name, Age = "Maimoona Khilji", 23

Name

Age

print(Name, Age)

print(Name, Age) # Age should have a capital A

# Make two variables separately
# Make two variables at once
# print them together and use different values for end and sep

## try to have a proper english name
# Try to avoid space in a variable name


Full_Name = "Maimoona Khilji"
Full_Name

Full_Name_111111 = "Maimoona Khilji"
Full_Name_111111

# Never start your variable name with numeric value
1_Full_Name = "Maimoona Khilji"

_Full_Name = "maimoona Khilji"
_Full_Name

Full_Name@ = "Maimoona khilji"

"""- Ways to define variable


1.   Use proper english word
2.   you can add numeric values after some alphabets
3.  You can add underscore at the start of variable


"""

number  = 1

Name  = "maimoona"
Name

Name = "khilji"
Name

"""# Data Types"""

Name = "Maimoona"
Name

Name = 'Maimoona'
Name

Name = '''My name is Maimoona.
'''
Name